# Generated by Django 3.2.6 on 2022-07-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataSource', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='house_totalPrice',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='house_unitPrice',
            new_name='unit_price',
        ),
    ]
